### ISSUE TITLE
bug: file mode specification error: (void-function: ion-mode)

### ISSUE THREAD

**Issue by matu3ba** [iwahbe/ion-mode#1]
commit f2536d3dd50203712301d2fc48f36296711f2342
Syntax highlighting is not shown.

Emacs 26.3
Placed in my emacs.d
`ion-mode`  
`init.el` has only
```
(add-to-list 'auto-mode-alist '("\\.ion\\'" . ion-mode))
```

fails (no syntax highlighting) with `file mode specification error: (void-function: ion-mode)`

A similar error happens on using 
```
(use-package ion-mode
  :straight (ion-mode
	       :host github :repo "iwahbe/ion-mode")
  :mode ("\\.ion\\'" . ion-mode)
  )
```

`Symbol's function definition is void: use-package`

**Comment by matu3ba** [comment]
Do I need to use something like
(autoload 'tuareg-mode "tuareg" "Major mode for editing Caml code" t) ?
https://stackoverflow.com/a/24254914

**Comment by iwahbe** [comment]
You need a require statement and it needs to be in your load path. 
When I test the mode I use this as my init:
```emacs list
(add-to-list 'load-path  "~/.emacs.d/straight/repos/ion-mode")

(require 'ion-mode)
(add-to-list 'auto-mode-alist '("\\.ion\\'" . ion-mode))
```
And it works for me. 
`use-package` and `straight` are packages themselves, so must be installed first. `use-package` is a macro system for a simple init file, and `straight` is a package manager.

**Comment by matu3ba** [comment]
@iwahbe Can you give me a minimal init.el file that only uses
```
stuff...
(add-to-list 'auto-mode-alist '("\\.ion\\'" . ion-mode))
stuff...
```
?
The instructions for installing packages were wrong or the server does not correctly list the packages (for example `use-package` could not be found). I am very surprised not to see a copy-paste-instruction, but this interactive windows-stuff, where you need to manually click and insert things.

**Comment by iwahbe** [comment]
I added a copy-paste instruction.

**Comment by matu3ba** [comment]
@iwahbe Cool, works. Thanks for the instructions.
